name: TrimCutShave
favicon: null
layout_spectrum: 0.50455
typography_spectrum: 0.50465
title: Trim Cute Shave
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060606'
    - '#ffffff'
    - '#7e572e'
    - '#807d88'
    - '#bab7c2'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose: []
